//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        public GamePlayer()
        {
            this.Active = true;
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public int Number { get; set; }
        public bool Active { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
