//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechTree.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Wins = 0;
            this.Losses = 0;
            this.CurrentGames = new HashSet<Game>();
            this.GamePlayers = new HashSet<GamePlayer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
    
        public virtual ICollection<Game> CurrentGames { get; set; }
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
    }
}
